### ISSUE TITLE
How to echo content into httpd.conf file?

### ISSUE THREAD

**Issue by zozidalom** [lipanski/docker-static-website#10]
Hi, I have the following Dockerfile:

```
FROM lipanski/docker-static-website:2.1.0

RUN echo "E404:index.html" > httpd.conf

COPY --from=build /app/dist/frontend .
```
I get the following error when I try to echo the content of the httpd.conf file:

`Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown`

How can I do this properly?

**Comment by lipanski** [comment]
@zozidalom the image doesn't have a shell, it runs [SCRATCH](https://hub.docker.com/_/scratch). so you can't really call `RUN` and even if you could, the `echo` command would also be missing.

the recommended way of pushing a `httpd.conf` is by placing it along your other files than end up _copied_ over.

since I see you're using a multi-stage build and if you don't want to mix the `httpd.conf` with your static files, an alternative would be to call `RUN echo "..." > httpd.conf` from within your other stage (`build`) and copy it over with `COPY --from=build /app/dist/frontend .`.

hope that helps.
