### ISSUE TITLE
propagate signals from image itself using tini (not sure if it's correct for busybox but something similar could be done maybe)

### ISSUE THREAD

**Issue by jkone27** [lipanski/docker-static-website#15]
https://github.com/krallin/tini

```dockerfile
# add sigterm and sigkill listen
RUN apk add --no-cache tini

WORKDIR /app
RUN chown -R node /app

USER node


#then not sure how you run the rest but ...
CMD [ "/sbin/tini", "--", "......entrypoint" ]
```

**Comment by lipanski** [comment]
@jkone27 while developing on your machine, you can run the container with `docker run --init` (which will propagate the signals to the container correctly) or stop the container with `docker stop` or `docker kill`. in any other environment (swarm, kubernetes etc.), the `TERM` signal is not relevant afaik and I can't think of any other relevant busybox signals that would need propagation. this is also mentioned in the README - look for the **NOTE** at the end of the *Usage* section.

I wouldn't want to add `tini` to the mix since I think the existing solutions are sufficient.
